version: "2"

services:
  php:
    volumes:
      - attabox-unison-sync:/var/www/html:rw # Replace volume to this to use docker-sync for macOS users

volumes:
  attabox-unison-sync:
    external: true
